version: 2

sources:
  - name: main
    schema: main
    tables:
      - name: campaigns
        description: "Marketing campaign master data"
        columns:
          - name: campaign_id
            description: "Unique identifier for campaigns"
            tests:
              - unique
              - not_null
      - name: leads
        description: "Lead generation data from campaigns"
        columns:
          - name: lead_id
            description: "Unique identifier for leads"
            tests:
              - unique
              - not_null
models:
  - name: stg_leads
    description: "Cleaned and standardized lead data"
    columns:
      - name: lead_id
        tests:
          - unique
          - not_null
      - name: campaign_id
        tests:
          - relationships:
              to: ref('stg_campaigns')
              field: campaign_id
      - name: created_at
      - name: lead_type

  - name: stg_campaigns
    description: "Cleaned and standardized campaign data"
    columns:
      - name: campaign_id
        tests:
          - unique
          - not_null
      - name: channel
      - name: campaign_name
      - name: start_date
      - name: end_date
      - name: budget
  
  - name: int_campaign_performance
    description: "Enriched campaign performance metrics"
    columns:
      - name: campaign_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_campaigns')
              field: campaign_id
      - name: leads_per_dollar
        description: "Lead generation efficiency metric"
        

  - name: dim_campaigns
    description: "Dimension table for campaigns"
    columns:
      - name: campaign_id
        tests:
          - not_null
          - unique
      - name: duration_days
        tests:
          - not_null
          

  - name: fct_daily_leads
    description: "Fact table for daily lead generation"
    columns:
      - name: date
        tests:
          - not_null
      - name: lead_count
        tests:
          - not_null
          